<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BoschHomeVn.Application\BoschHomeVn.Application.csproj" />
    <ProjectReference Include="..\BoschHomeVn.Domain\BoschHomeVn.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\Seed\*.seed.json" />
  </ItemGroup>

</Project>
