using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BoschHomeVn.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261010170000_SeedNewsSamples")]
    public partial class SeedNewsSamples : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
INSERT INTO "NewsCategories" ("Id", "Name", "Description", "SortOrder")
SELECT 'meo-hay-nha-bep', 'Mẹo hay nhà bếp', 'Mẹo nhỏ giúp nấu nướng, bảo quản thực phẩm và giữ căn bếp gọn gàng hơn mỗi ngày.', (SELECT COALESCE(MAX("SortOrder"), -1) + 1 FROM "NewsCategories")
WHERE NOT EXISTS (SELECT 1 FROM "NewsCategories" WHERE "Id" = 'meo-hay-nha-bep' OR lower("Name") = lower('Mẹo hay nhà bếp'));

INSERT INTO "NewsCategories" ("Id", "Name", "Description", "SortOrder")
SELECT 'mon-ngon-moi-ngay', 'Món ngon mỗi ngày', 'Gợi ý món ngon và mẹo nấu nướng với thiết bị Bosch cho bữa ăn gia đình.', (SELECT COALESCE(MAX("SortOrder"), -1) + 1 FROM "NewsCategories")
WHERE NOT EXISTS (SELECT 1 FROM "NewsCategories" WHERE "Id" = 'mon-ngon-moi-ngay' OR lower("Name") = lower('Món ngon mỗi ngày'));

INSERT INTO "NewsCategories" ("Id", "Name", "Description", "SortOrder")
SELECT 'huong-dan-su-dung', 'Hướng dẫn sử dụng', 'Cách dùng và chăm sóc thiết bị Bosch đúng cách để luôn bền và hiệu quả.', (SELECT COALESCE(MAX("SortOrder"), -1) + 1 FROM "NewsCategories")
WHERE NOT EXISTS (SELECT 1 FROM "NewsCategories" WHERE "Id" = 'huong-dan-su-dung' OR lower("Name") = lower('Hướng dẫn sử dụng'));

INSERT INTO "NewsCategories" ("Id", "Name", "Description", "SortOrder")
SELECT 'kinh-nghiem-chon-mua', 'Kinh nghiệm chọn mua', 'Những điều nên cân nhắc trước khi chọn thiết bị cho gia đình.', (SELECT COALESCE(MAX("SortOrder"), -1) + 1 FROM "NewsCategories")
WHERE NOT EXISTS (SELECT 1 FROM "NewsCategories" WHERE "Id" = 'kinh-nghiem-chon-mua' OR lower("Name") = lower('Kinh nghiệm chọn mua'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", 'Tủ lạnh nhiều cửa hay side by side: chọn sao cho hợp căn bếp?', 'tu-lanh-nhieu-cua-hay-side-by-side', 'Hai kiểu tủ lạnh dung tích lớn phổ biến nhất có cách bố trí ngăn rất khác nhau. Đây là những điểm nên so sánh trước khi quyết định.', '/media/news/seed-tu-lanh-nhieu-cua-hay-side-by-side.jpg',
'<p>Khi gia đình cần tủ lạnh dung tích lớn, lựa chọn thường xoay quanh hai kiểu: <strong>nhiều cửa</strong> (kiểu Pháp, ngăn đá dưới) và <strong>side by side</strong> (hai cánh mở dọc). Cả hai đều rộng rãi, nhưng hợp với những thói quen khác nhau.</p><h2>Tủ lạnh nhiều cửa: ngăn mát ngang tầm mắt</h2><p>Ngăn mát nằm phía trên với hai cánh mở, ngăn đá ở dưới dạng ngăn kéo. Thực phẩm dùng hằng ngày luôn ở tầm mắt, không phải cúi người. Ngăn mát rộng theo chiều ngang nên dễ để khay lớn, bánh kem hay nồi lẩu.</p><ul><li>Hợp với gia đình dùng ngăn mát nhiều hơn ngăn đá.</li><li>Ngăn kéo đá giúp nhìn thấy đồ đông lạnh từ trên xuống, ít bị quên đồ.</li></ul><h2>Side by side: ngăn đá cao, chia đôi rõ ràng</h2><p>Ngăn đá và ngăn mát nằm cạnh nhau theo chiều dọc. Ngăn đá cao nên chứa được nhiều đồ đông lạnh, hợp với nhà hay trữ thịt cá. Cánh tủ hẹp hơn nên cần ít khoảng trống phía trước khi mở.</p><ul><li>Hợp với gia đình trữ nhiều đồ đông lạnh.</li><li>Ngăn mát hẹp theo chiều ngang, khó để khay quá rộng.</li></ul><h2>Đo không gian trước khi chọn</h2><p>Đo chiều rộng, chiều cao và chiều sâu chỗ đặt tủ, cộng thêm khoảng hở vài centimet ở hai bên và phía sau để tủ tản nhiệt. Đừng quên kiểm tra lối đi và khung cửa để tủ vào được tận nơi.</p><p>Nếu vẫn phân vân, hãy gọi hotline 1900 6868 để được tư vấn mẫu phù hợp với kích thước căn bếp của bạn.</p>',
TRUE, TIMESTAMPTZ '2026-10-08T09:00:00+07:00', TIMESTAMPTZ '2026-10-08T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'kinh-nghiem-chon-mua' OR lower("Name") = lower('Kinh nghiệm chọn mua') ORDER BY ("Id" = 'kinh-nghiem-chon-mua') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 'tu-lanh-nhieu-cua-hay-side-by-side' OR lower("Title") = lower('Tủ lạnh nhiều cửa hay side by side: chọn sao cho hợp căn bếp?'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", 'Vệ sinh máy rửa bát định kỳ: 4 bước trong 15 phút', 've-sinh-may-rua-bat-dinh-ky', 'Lưới lọc, tay phun và gioăng cửa là ba chỗ cần chăm sóc để máy luôn rửa sạch và không có mùi.', '/media/news/seed-ve-sinh-may-rua-bat-dinh-ky.jpg',
'<p>Máy rửa bát làm sạch bát đĩa, nhưng bản thân máy cũng cần được chăm sóc. Dành khoảng 15 phút mỗi tháng cho các bước dưới đây giúp máy rửa sạch hơn, ít mùi và bền hơn.</p><h2>1. Rửa cụm lưới lọc</h2><p>Cụm lọc nằm ở đáy khoang rửa. Xoay ngược chiều kim đồng hồ để tháo, rửa dưới vòi nước và dùng bàn chải mềm chải sạch cặn thức ăn. Lắp lại đúng vị trí và xoay đến khi khớp chặt.</p><h2>2. Kiểm tra tay phun</h2><p>Xoay thử tay phun bằng tay. Nếu bị kẹt hoặc lỗ phun bị tắc, hãy tháo ra và dùng tăm thông các lỗ. Tay phun quay trơn tru thì nước mới tới được mọi góc của giàn bát.</p><h2>3. Lau gioăng cửa và cạnh cửa</h2><p>Dùng khăn ẩm lau sạch gioăng cao su và mép cửa, nơi dầu mỡ dễ đọng lại. Không dùng chất tẩy mạnh hoặc vật sắc để tránh làm hỏng gioăng.</p><h2>4. Chạy một chu trình vệ sinh</h2><p>Khi máy trống, chạy chương trình nhiệt độ cao nhất với dung dịch vệ sinh máy rửa bát chuyên dụng để loại bỏ cặn vôi và dầu mỡ bám trong đường ống.</p><h2>Thói quen nhỏ giúp máy luôn sạch</h2><ul><li>Gạt bỏ thức ăn thừa trước khi xếp bát, không cần tráng lại bằng nước.</li><li>Thường xuyên kiểm tra và bổ sung muối làm mềm nước, nước làm bóng.</li><li>Để hé cửa sau khi rửa xong cho khoang máy khô thoáng.</li></ul>',
TRUE, TIMESTAMPTZ '2026-10-05T09:00:00+07:00', TIMESTAMPTZ '2026-10-05T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'huong-dan-su-dung' OR lower("Name") = lower('Hướng dẫn sử dụng') ORDER BY ("Id" = 'huong-dan-su-dung') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 've-sinh-may-rua-bat-dinh-ky' OR lower("Title") = lower('Vệ sinh máy rửa bát định kỳ: 4 bước trong 15 phút'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", 'Bảo quản rau củ tươi lâu với ngăn rau của tủ lạnh', 'bao-quan-rau-cu-tuoi-lau', 'Đúng nhiệt độ, đúng độ ẩm và đúng cách đóng gói là ba yếu tố giúp rau củ giữ được độ giòn và màu tươi lâu hơn.', '/media/news/seed-bao-quan-rau-cu-tuoi-lau.jpg',
'<p>Rau củ mua về để vài hôm đã héo là chuyện quen thuộc. Thực ra chỉ cần sắp xếp lại một chút, ngăn rau của tủ lạnh có thể giữ rau tươi lâu hơn đáng kể.</p><h2>Để rau ở đúng ngăn</h2><p>Ngăn rau phía dưới có độ ẩm cao hơn các tầng khác, hợp cho rau lá và củ quả. Nhiều dòng tủ lạnh Bosch có ngăn VitaFresh cho phép điều chỉnh độ ẩm, giúp rau lá giữ được độ giòn.</p><h2>Sơ chế nhẹ trước khi cất</h2><ul><li>Nhặt bỏ lá úa, dập nát vì chúng làm phần còn lại hỏng nhanh hơn.</li><li>Không rửa rau trước khi cất; nếu đã rửa, để thật ráo nước.</li><li>Bọc rau lá trong khăn giấy rồi cho vào túi hoặc hộp có lỗ thoáng.</li></ul><h2>Tách riêng trái cây sinh khí ethylene</h2><p>Táo, chuối, bơ, cà chua tiết ra khí ethylene làm rau củ nhanh chín và héo. Hãy để chúng ở ngăn riêng hoặc trong hộp kín, cách xa rau lá.</p><h2>Giữ nhiệt độ ổn định</h2><p>Ngăn mát nên ở khoảng 3–5°C. Hạn chế mở cửa tủ lâu và không xếp đồ quá chật để khí lạnh lưu thông đều.</p>',
TRUE, TIMESTAMPTZ '2026-09-28T09:00:00+07:00', TIMESTAMPTZ '2026-09-28T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'meo-hay-nha-bep' OR lower("Name") = lower('Mẹo hay nhà bếp') ORDER BY ("Id" = 'meo-hay-nha-bep') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 'bao-quan-rau-cu-tuoi-lau' OR lower("Title") = lower('Bảo quản rau củ tươi lâu với ngăn rau của tủ lạnh'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", 'Chọn chương trình và nhiệt độ giặt phù hợp từng loại vải', 'chon-chuong-trinh-giat-phu-hop', 'Giặt đúng chương trình giúp quần áo sạch hơn, bền màu hơn và tiết kiệm điện nước. Đây là cách chọn nhanh cho các loại vải thường gặp.', '/media/news/seed-chon-chuong-trinh-giat-phu-hop.jpg',
'<p>Máy giặt hiện đại có rất nhiều chương trình, nhưng phần lớn gia đình chỉ dùng một hai chế độ quen thuộc. Chọn đúng chương trình cho từng loại vải giúp quần áo bền hơn và tiết kiệm điện nước.</p><h2>Đọc nhãn mác trước khi giặt</h2><p>Ký hiệu chậu nước trên nhãn cho biết nhiệt độ giặt tối đa. Nhãn có hình bàn tay nghĩa là chỉ nên giặt tay hoặc dùng chương trình giặt tay, đồ len của máy.</p><h2>Gợi ý theo loại vải</h2><ul><li><strong>Cotton:</strong> chương trình Cotton, 30–40°C cho đồ thường; 60°C cho khăn tắm, ga gối cần làm sạch kỹ.</li><li><strong>Vải tổng hợp, đồ thể thao:</strong> chương trình Synthetic hoặc Sportswear, nhiệt độ thấp, vắt nhẹ.</li><li><strong>Len, lụa:</strong> chương trình Wool hoặc Delicate, nước lạnh, vắt tốc độ thấp.</li><li><strong>Chăn, rèm:</strong> chương trình đồ cồng kềnh, không giặt quá tải.</li></ul><h2>Đừng giặt quá đầy</h2><p>Lồng giặt nên còn khoảng một gang tay phía trên để quần áo đảo đều. Với đồ dày như chăn, nên giặt ít hơn khối lượng tối đa của máy.</p><h2>Dùng lượng nước giặt vừa đủ</h2><p>Nhiều nước giặt không làm đồ sạch hơn mà còn để lại cặn trên vải và trong máy. Một số dòng máy giặt Bosch có tính năng định lượng tự động i-DOS, tự châm lượng nước giặt phù hợp với lượng đồ.</p>',
TRUE, TIMESTAMPTZ '2026-09-30T09:00:00+07:00', TIMESTAMPTZ '2026-09-30T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'huong-dan-su-dung' OR lower("Name") = lower('Hướng dẫn sử dụng') ORDER BY ("Id" = 'huong-dan-su-dung') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 'chon-chuong-trinh-giat-phu-hop' OR lower("Title") = lower('Chọn chương trình và nhiệt độ giặt phù hợp từng loại vải'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", '6 mẹo nướng bánh quy giòn đều bằng lò nướng', 'meo-nuong-banh-quy-gion-deu', 'Từ làm nóng lò đến chọn khay và vị trí nướng, vài thay đổi nhỏ giúp mẻ bánh chín vàng đều từ trong ra ngoài.', '/media/news/seed-meo-nuong-banh-quy-gion-deu.jpg',
'<p>Bánh quy nhìn đơn giản nhưng rất dễ cháy cạnh hoặc sống giữa. Sáu mẹo dưới đây giúp mẻ bánh tiếp theo vàng đều và giòn hơn.</p><ol><li><strong>Luôn làm nóng lò trước.</strong> Đợi lò đạt đủ nhiệt rồi mới cho bánh vào để bánh nở và chín đều.</li><li><strong>Chọn chế độ quạt đối lưu</strong> khi nướng nhiều khay cùng lúc, giúp nhiệt lan đều các tầng.</li><li><strong>Dùng khay sáng màu, lót giấy nến.</strong> Khay tối màu hấp nhiệt mạnh, dễ làm đáy bánh cháy.</li><li><strong>Chia bánh đều kích thước</strong> và chừa khoảng cách để bánh không dính vào nhau khi nở.</li><li><strong>Nướng ở tầng giữa</strong> nếu chỉ có một khay; hạn chế mở cửa lò trong lúc nướng.</li><li><strong>Để bánh nguội trên giá</strong> vài phút trước khi lấy ra, bánh sẽ giòn hơn.</li></ol><h2>Vệ sinh lò sau khi nướng</h2><p>Khi lò đã nguội bớt, lau sạch vụn bánh và dầu mỡ bằng khăn ẩm. Một số lò nướng Bosch có chức năng tự làm sạch giúp việc vệ sinh nhẹ nhàng hơn.</p>',
TRUE, TIMESTAMPTZ '2026-10-02T09:00:00+07:00', TIMESTAMPTZ '2026-10-02T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'mon-ngon-moi-ngay' OR lower("Name") = lower('Món ngon mỗi ngày') ORDER BY ("Id" = 'mon-ngon-moi-ngay') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 'meo-nuong-banh-quy-gion-deu' OR lower("Title") = lower('6 mẹo nướng bánh quy giòn đều bằng lò nướng'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", 'Máy giặt cửa trước: chọn khối lượng giặt bao nhiêu kg là đủ?', 'chon-khoi-luong-may-giat', 'Khối lượng giặt phù hợp giúp máy chạy hiệu quả, tiết kiệm điện nước và giặt được cả chăn ga khi cần.', '/media/news/seed-chon-khoi-luong-may-giat.jpg',
'<p>Khối lượng giặt là con số đầu tiên cần cân nhắc khi chọn máy giặt. Máy quá nhỏ phải giặt nhiều lần, máy quá lớn lại lãng phí nếu thường chỉ giặt ít đồ.</p><h2>Gợi ý theo số thành viên</h2><ul><li><strong>1–2 người:</strong> khoảng 8 kg là đủ cho nhu cầu hằng ngày.</li><li><strong>3–4 người:</strong> 9 kg, giặt thoải mái quần áo cả tuần và chăn mỏng.</li><li><strong>5 người trở lên:</strong> 10 kg trở lên, hợp khi thường xuyên giặt chăn ga, rèm cửa.</li></ul><h2>Đừng quên kích thước lắp đặt</h2><p>Máy giặt cửa trước cần khoảng trống phía trước để mở cửa và lấy đồ. Đo chiều sâu chỗ đặt máy, cộng thêm khoảng hở phía sau cho đường ống cấp và xả nước.</p><h2>Những tính năng nên có</h2><ul><li>Động cơ Inverter chạy êm, tiết kiệm điện.</li><li>Chương trình giặt nhanh cho đồ ít bẩn.</li><li>Chương trình chăn ga, đồ cồng kềnh.</li><li>Hẹn giờ kết thúc để giặt vào giờ phù hợp.</li></ul><p>Bạn có thể xem các mẫu máy giặt Bosch đang bán trong mục Gia dụng hoặc gọi 1900 6868 để được tư vấn.</p>',
TRUE, TIMESTAMPTZ '2026-09-24T09:00:00+07:00', TIMESTAMPTZ '2026-09-24T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'kinh-nghiem-chon-mua' OR lower("Name") = lower('Kinh nghiệm chọn mua') ORDER BY ("Id" = 'kinh-nghiem-chon-mua') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 'chon-khoi-luong-may-giat' OR lower("Title") = lower('Máy giặt cửa trước: chọn khối lượng giặt bao nhiêu kg là đủ?'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", 'Dùng bếp từ đúng cách: nồi chảo phù hợp và giữ mặt kính bền đẹp', 'dung-bep-tu-dung-cach', 'Bếp từ chỉ hoạt động với nồi có đáy nhiễm từ. Biết cách chọn nồi và vệ sinh mặt kính giúp bếp nấu nhanh và luôn sáng bóng.', '/media/news/seed-dung-bep-tu-dung-cach.jpg',
'<p>Bếp từ làm nóng trực tiếp đáy nồi nên nấu nhanh và an toàn hơn bếp gas. Để bếp phát huy hết hiệu quả, hãy lưu ý vài điều sau.</p><h2>Nồi chảo nào dùng được?</h2><p>Bếp từ chỉ nhận nồi có đáy nhiễm từ như inox 430, gang, thép tráng men. Cách thử nhanh: đưa nam châm lại gần đáy nồi, nếu hút chặt là dùng được.</p><ul><li>Chọn nồi đáy phẳng, đường kính gần bằng vùng nấu.</li><li>Nồi nhôm, thủy tinh, gốm thường không dùng được trừ khi có lớp đáy từ.</li></ul><h2>Nấu tiết kiệm điện</h2><ul><li>Đặt nồi đúng giữa vùng nấu.</li><li>Dùng mức công suất cao để đun sôi rồi hạ xuống để giữ sôi.</li><li>Đậy nắp khi nấu để giữ nhiệt.</li></ul><h2>Vệ sinh mặt kính</h2><p>Đợi mặt bếp nguội rồi lau bằng khăn mềm và dung dịch chuyên dụng cho mặt kính. Với vết bám cứng, dùng dao cạo chuyên dụng cho bếp kính, tránh miếng cọ kim loại làm xước bề mặt.</p><p>Không kéo lê nồi trên mặt kính và lau ngay khi thức ăn có đường bị trào để tránh để lại vết.</p>',
TRUE, TIMESTAMPTZ '2026-09-20T09:00:00+07:00', TIMESTAMPTZ '2026-09-20T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'huong-dan-su-dung' OR lower("Name") = lower('Hướng dẫn sử dụng') ORDER BY ("Id" = 'huong-dan-su-dung') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 'dung-bep-tu-dung-cach' OR lower("Title") = lower('Dùng bếp từ đúng cách: nồi chảo phù hợp và giữ mặt kính bền đẹp'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", 'Pha cà phê ngon mỗi sáng với máy pha tự động', 'pha-ca-phe-ngon-moi-sang', 'Hạt cà phê, độ xay và cách đánh sữa quyết định phần lớn hương vị. Vài điều chỉnh nhỏ giúp ly cà phê đậm đà đúng gu.', '/media/news/seed-pha-ca-phe-ngon-moi-sang.jpg',
'<p>Máy pha cà phê tự động cho bạn ngay một ly espresso hay cappuccino chỉ với một nút bấm. Để ly cà phê ngon hơn, bạn có thể tinh chỉnh vài thiết lập.</p><h2>Chọn hạt và bảo quản đúng cách</h2><ul><li>Dùng hạt rang vừa hoặc rang đậm cho espresso; hạt mới rang trong vòng vài tuần cho hương thơm tốt nhất.</li><li>Đậy kín ngăn chứa hạt, tránh nắng và nơi nóng ẩm.</li></ul><h2>Điều chỉnh độ xay và độ đậm</h2><p>Xay mịn hơn cho vị đậm, xay thô hơn nếu cà phê bị đắng gắt. Thay đổi từng nấc nhỏ và thử qua vài ly để tìm mức phù hợp.</p><h2>Đánh sữa mịn cho cappuccino</h2><p>Dùng sữa tươi lạnh, sữa có độ béo cao cho lớp bọt dày và mịn. Vệ sinh vòi đánh sữa ngay sau mỗi lần dùng để sữa không đóng cặn.</p><h2>Bảo dưỡng định kỳ</h2><ul><li>Đổ bã và rửa khay hứng nước mỗi ngày.</li><li>Chạy chương trình tẩy cặn khi máy báo, nhất là ở nơi nước cứng.</li><li>Thay lõi lọc nước theo khuyến nghị của nhà sản xuất.</li></ul>',
TRUE, TIMESTAMPTZ '2026-09-22T09:00:00+07:00', TIMESTAMPTZ '2026-09-22T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'mon-ngon-moi-ngay' OR lower("Name") = lower('Món ngon mỗi ngày') ORDER BY ("Id" = 'mon-ngon-moi-ngay') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 'pha-ca-phe-ngon-moi-sang' OR lower("Title") = lower('Pha cà phê ngon mỗi sáng với máy pha tự động'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", 'Dùng máy sấy bơm nhiệt sao cho tiết kiệm và giữ quần áo bền', 'dung-may-say-bom-nhiet-tiet-kiem', 'Máy sấy bơm nhiệt sấy ở nhiệt độ thấp nên êm với sợi vải. Vài thói quen nhỏ giúp máy sấy nhanh và tiết kiệm điện hơn.', '/media/news/seed-dung-may-say-bom-nhiet-tiet-kiem.jpg',
'<p>Máy sấy bơm nhiệt dùng không khí ấm ở nhiệt độ thấp hơn máy sấy thông thường, nhờ đó tiết kiệm điện và nhẹ nhàng hơn với quần áo. Để máy chạy hiệu quả, hãy lưu ý vài điều sau.</p><h2>Vắt kỹ trước khi sấy</h2><p>Chọn tốc độ vắt cao nhất mà loại vải cho phép. Quần áo càng ít nước, thời gian sấy càng ngắn.</p><h2>Phân loại đồ theo chất liệu</h2><ul><li>Sấy riêng đồ dày (khăn tắm, jeans) và đồ mỏng để đồ khô đều.</li><li>Kiểm tra nhãn mác, không sấy đồ có ký hiệu cấm sấy.</li></ul><h2>Vệ sinh bộ lọc sau mỗi lần sấy</h2><p>Bộ lọc xơ vải ở cửa máy cần được làm sạch sau mỗi mẻ. Bộ lọc bám xơ làm luồng khí yếu, máy sấy lâu và tốn điện hơn. Định kỳ vệ sinh cả bộ lọc ở dàn trao đổi nhiệt theo hướng dẫn của máy.</p><h2>Đổ nước ngưng</h2><p>Nếu máy không nối ống xả, hãy đổ bình chứa nước ngưng sau mỗi lần sấy để máy không phải dừng giữa chừng.</p>',
TRUE, TIMESTAMPTZ '2026-09-13T09:00:00+07:00', TIMESTAMPTZ '2026-09-13T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'huong-dan-su-dung' OR lower("Name") = lower('Hướng dẫn sử dụng') ORDER BY ("Id" = 'huong-dan-su-dung') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 'dung-may-say-bom-nhiet-tiet-kiem' OR lower("Title") = lower('Dùng máy sấy bơm nhiệt sao cho tiết kiệm và giữ quần áo bền'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", 'Giữ máy hút mùi luôn sạch và hút mạnh', 've-sinh-may-hut-mui', 'Lưới lọc mỡ bám bẩn làm máy hút yếu và ồn hơn. Vệ sinh đúng cách giúp căn bếp luôn thoáng mùi.', '/media/news/seed-ve-sinh-may-hut-mui.jpg',
'<p>Máy hút mùi làm việc mỗi khi bạn nấu nướng, và lưới lọc mỡ là bộ phận gánh nhiều dầu mỡ nhất. Khi lưới bị bám bẩn, máy hút yếu hơn, ồn hơn và mùi thức ăn dễ lan khắp nhà.</p><h2>Vệ sinh lưới lọc mỡ</h2><p>Lưới lọc kim loại nên được vệ sinh khoảng 1–2 tháng một lần, thường xuyên hơn nếu gia đình hay chiên xào. Tháo lưới theo hướng dẫn của máy, ngâm nước ấm pha nước rửa chén rồi chải nhẹ. Nhiều loại lưới lọc kim loại có thể rửa bằng máy rửa bát.</p><h2>Thay lõi lọc than hoạt tính</h2><p>Với máy hút mùi chạy chế độ tuần hoàn (không có ống thoát ra ngoài), lõi than hoạt tính giữ lại mùi và không rửa được. Hãy thay lõi định kỳ theo khuyến nghị của nhà sản xuất.</p><h2>Thói quen khi nấu</h2><ul><li>Bật máy hút mùi vài phút trước khi bắt đầu nấu để tạo luồng hút ổn định.</li><li>Để máy chạy thêm 10–15 phút sau khi nấu xong để hút hết hơi nóng và mùi còn lại.</li><li>Dùng mức hút cao khi chiên rán, mức thấp khi hầm, luộc.</li></ul><h2>Lau thân máy</h2><p>Lau mặt kính và thân máy bằng khăn mềm, ẩm. Tránh dùng miếng cọ kim loại hoặc chất tẩy có tính mài mòn làm xước bề mặt.</p>',
TRUE, TIMESTAMPTZ '2026-09-26T09:00:00+07:00', TIMESTAMPTZ '2026-09-26T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'meo-hay-nha-bep' OR lower("Name") = lower('Mẹo hay nhà bếp') ORDER BY ("Id" = 'meo-hay-nha-bep') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 've-sinh-may-hut-mui' OR lower("Title") = lower('Giữ máy hút mùi luôn sạch và hút mạnh'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", 'Hâm nóng và rã đông bằng lò vi sóng đúng cách', 'ham-nong-ra-dong-bang-lo-vi-song', 'Lò vi sóng giúp bữa ăn sẵn sàng chỉ trong vài phút. Vài mẹo nhỏ giúp thức ăn nóng đều, giữ được độ ẩm và hương vị.', '/media/news/seed-ham-nong-ra-dong-bang-lo-vi-song.jpg',
'<p>Lò vi sóng là trợ thủ quen thuộc cho những bữa ăn vội. Để thức ăn hâm nóng đều và rã đông không bị chín một phần, hãy thử vài mẹo dưới đây.</p><h2>Hâm nóng đều hơn</h2><ul><li>Dàn mỏng thức ăn trên đĩa, phần dày ra mép ngoài, phần mỏng vào giữa.</li><li>Đậy nắp chuyên dụng cho lò vi sóng để giữ hơi ẩm và tránh văng bẩn.</li><li>Hâm từng đợt ngắn, đảo đều giữa các lần để nhiệt lan khắp món ăn.</li><li>Để thức ăn nghỉ khoảng một phút sau khi hâm để nhiệt độ cân bằng.</li></ul><h2>Rã đông nhanh mà không chín mép</h2><p>Dùng chế độ rã đông theo khối lượng nếu lò có. Lật mặt thực phẩm giữa chừng và tách các miếng đã mềm ra trước. Nên chế biến ngay sau khi rã đông, không cấp đông lại.</p><h2>Dụng cụ dùng được trong lò vi sóng</h2><p>Dùng hộp thủy tinh, sứ hoặc nhựa có ký hiệu dùng được cho lò vi sóng. Không cho vật dụng kim loại, giấy bạc hoặc bát đĩa viền kim loại vào lò khi dùng chế độ vi sóng.</p><h2>Vệ sinh nhanh khoang lò</h2><p>Đặt một bát nước pha chút nước cốt chanh vào lò, chạy vài phút cho hơi nước làm mềm vết bẩn, rồi lau sạch bằng khăn ẩm.</p>',
TRUE, TIMESTAMPTZ '2026-09-18T09:00:00+07:00', TIMESTAMPTZ '2026-09-18T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'mon-ngon-moi-ngay' OR lower("Name") = lower('Món ngon mỗi ngày') ORDER BY ("Id" = 'mon-ngon-moi-ngay') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 'ham-nong-ra-dong-bang-lo-vi-song' OR lower("Title") = lower('Hâm nóng và rã đông bằng lò vi sóng đúng cách'));

INSERT INTO "NewsPosts" ("Id", "CategoryId", "Title", "Slug", "Summary", "CoverImageUrl", "Html", "IsPublished", "PublishedAt", "UpdatedAt")
SELECT gen_random_uuid(), c."Id", 'Lò nướng âm tủ: chọn dung tích và chức năng nào?', 'chon-lo-nuong-am-tu', 'Dung tích, chế độ nướng và cách vệ sinh là ba điểm nên so sánh khi chọn lò nướng âm tủ cho căn bếp gia đình.', '/media/news/seed-chon-lo-nuong-am-tu.jpg',
'<p>Lò nướng âm tủ giúp căn bếp gọn gàng và nướng được những mẻ lớn. Trước khi chọn, hãy cân nhắc vài yếu tố sau.</p><h2>Dung tích</h2><p>Phần lớn lò nướng âm tủ tiêu chuẩn có dung tích khoảng 65–71 lít, đủ cho gà nguyên con hay hai khay bánh cùng lúc. Gia đình ít người hoặc chủ yếu hâm nóng có thể cân nhắc lò kết hợp vi sóng nhỏ gọn hơn.</p><h2>Chế độ nướng nên có</h2><ul><li><strong>Quạt đối lưu:</strong> nướng nhiều tầng cùng lúc, nhiệt lan đều.</li><li><strong>Nướng trên dưới truyền thống:</strong> hợp cho bánh bông lan, bánh mì.</li><li><strong>Nướng vỉ (grill):</strong> làm vàng mặt món ăn, nướng thịt.</li><li><strong>Hâm nóng, rã đông, giữ ấm:</strong> tiện cho bữa ăn hằng ngày.</li></ul><h2>Cách vệ sinh</h2><p>Một số dòng lò có chức năng tự làm sạch hoặc lớp men dễ lau chùi, giúp tiết kiệm thời gian vệ sinh sau khi nướng.</p><h2>Kích thước lắp đặt</h2><p>Khoang tủ cho lò âm tiêu chuẩn thường rộng 60 cm, cao khoảng 60 cm. Lò có thể lắp dưới mặt bếp hoặc trong cột tủ cao ngang tầm mắt để thao tác thuận tiện hơn.</p>',
TRUE, TIMESTAMPTZ '2026-09-16T09:00:00+07:00', TIMESTAMPTZ '2026-09-16T09:00:00+07:00'
FROM (SELECT "Id" FROM "NewsCategories" WHERE "Id" = 'kinh-nghiem-chon-mua' OR lower("Name") = lower('Kinh nghiệm chọn mua') ORDER BY ("Id" = 'kinh-nghiem-chon-mua') DESC LIMIT 1) c
WHERE NOT EXISTS (SELECT 1 FROM "NewsPosts" WHERE "Slug" = 'chon-lo-nuong-am-tu' OR lower("Title") = lower('Lò nướng âm tủ: chọn dung tích và chức năng nào?'));
""");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DELETE FROM "NewsPosts" WHERE "Slug" IN ('tu-lanh-nhieu-cua-hay-side-by-side', 've-sinh-may-rua-bat-dinh-ky', 'bao-quan-rau-cu-tuoi-lau', 'chon-chuong-trinh-giat-phu-hop', 'meo-nuong-banh-quy-gion-deu', 'chon-khoi-luong-may-giat', 'dung-bep-tu-dung-cach', 'pha-ca-phe-ngon-moi-sang', 'dung-may-say-bom-nhiet-tiet-kiem', 've-sinh-may-hut-mui', 'ham-nong-ra-dong-bang-lo-vi-song', 'chon-lo-nuong-am-tu');
DELETE FROM "NewsCategories" c WHERE c."Id" IN ('huong-dan-su-dung', 'kinh-nghiem-chon-mua', 'mon-ngon-moi-ngay')
  AND NOT EXISTS (SELECT 1 FROM "NewsPosts" p WHERE p."CategoryId" = c."Id");
""");
        }
    }
}
